### PR TITLE
Maintenance: iOS 18.1 / Swift 6 compatibility, Fix Deprecations, Rudimentary Fog Node CI testing, Bump Fog Node JS Dependencies

### PR DESCRIPTION
**Pull request by philippzagar**
# Maintenance: iOS 18.1 / Swift 6 compatibility, Fix Deprecations, Rudimentary Fog Node CI testing, Bump Fog Node JS Dependencies

## :recycle: Current situation & Problem
Repo wasn't really maintained in the last months, therefore lots of things became a bit out of date.

## :gear: Release Notes 
- iOS 18.1 / Swift 6 compatibility
- Fix Deprecations
- Bump Fog Node JS dependencies
- Rudimentary Fog Node CI testing

## :books: Documentation
--

## :white_check_mark: Testing
--

## :pencil: Code of Conduct & Contributing Guidelines 

By submitting creating this pull request, you agree to follow our [Code of Conduct](https://github.com/StanfordSpezi/.github/blob/main/CODE_OF_CONDUCT.md) and [Contributing Guidelines](https://github.com/StanfordSpezi/.github/blob/main/CONTRIBUTING.md):
- [x] I agree to follow the [Code of Conduct](https://github.com/StanfordSpezi/.github/blob/main/CODE_OF_CONDUCT.md) and [Contributing Guidelines](https://github.com/StanfordSpezi/.github/blob/main/CONTRIBUTING.md).

### CODE REVIEW

**Comment by PSchmiedmayer** [comment]
@philippzagar Thank you for working on this and merging it in a single PR!

I see that that there are a lot of iOS elements failing, let me know if you need any help from someone there. I think the issues might be related to some Xcode updates and Simulators available on the runners?

**Comment by philippzagar** [comment]
> I see that that there are a lot of iOS elements failing, let me know if you need any help from someone there. I think the issues might be related to some Xcode updates and Simulators available on the runners?

Currently investigating that, you were right, the issue seems to be in the UI tests with `TextFields` vs `TextViews`, seems to be an iOS 18 (or 18.1?) change.
Weil let you know as soon as the PR is ready!

**Comment by philippzagar** [comment]
@PSchmiedmayer So, PR should be ready now, in general I did a bit of maintenance work in the PR.
Most of the `retroactive` conformances (dangerous!) will soon be redudndant as soon as #64 is merged!

**Comment by philippzagar** [comment]
@PSchmiedmayer Could you grant me admin access to the repo? Then I can e.g. set new CI jobs as required by this change on my own.

**Review by PSchmiedmayer — APPROVED** [review]
Nice; looks great @philippzagar!

**Pull request merged**
